version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.0.5-sdk-2.1.4-stretch
      - image: nats:1.0.4-linux
        name: nats-0
      - image: nats:1.0.4-linux
        name: nats-1
        command: -p 4223 -c gnatsd.conf --routes=nats-route://ruser:T0pS3cr3t@nats-0:6222
    steps:
      - checkout
      - run: 
          name: Build solution
          command: |
            dotnet restore
            dotnet build -c Release --version-suffix $CIRCLE_BUILD_NUM
      - run:
          name: Unit Tests
          working_directory: ./SimpleNatsClient.Tests
          command: dotnet test --no-build -c Release
      - run:
          name: Integration Tests
          working_directory: ./SimpleNatsClient.IntegrationTests
          command: dotnet test --no-build -c Release
      - run:
          name: Deploy Nuget
          working_directory: ./SimpleNatsClient
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              dotnet nuget push ./bin/Release/SimpleNatsClient\*.nupkg -s nuget.org -k $NUGET_APIKEY
            fi
